#!/bin/bash
#
# Copyright (c) 2013-2021 Igor Pecovnik, igor.pecovnik@gma**.com
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.

# DO NOT EDIT THIS FILE
# use configuration files like config-default.conf to set the build configuration

SRC="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# check for whitespace in ${SRC} and exit for safety reasons
grep -q "[[:space:]]" <<<"${SRC}" && { echo "\"${SRC}\" contains whitespace. Not supported. Aborting." >&2 ; exit 1 ; }

cd "${SRC}" || exit

if [[ "${ORANGEPI_ENABLE_CALL_TRACING}" == "yes" ]]; then
	set -T # inherit return/debug traps
	mkdir -p "${SRC}"/output/debug
	echo -n "" > "${SRC}"/output/debug/calls.txt
	trap 'echo "${BASH_LINENO[@]}|${BASH_SOURCE[@]}|${FUNCNAME[@]}" >> ${SRC}/output/debug/calls.txt ;' RETURN
fi

if [[ -f "${SRC}"/scripts/general.sh ]]; then
	# shellcheck source=scripts/general.sh
	source "${SRC}"/scripts/general.sh
else
	echo "Error: missing build directory structure"
	exit 255
fi

#  Add the variables needed at the beginning of the path
check_args ()
{
    for p in "$@"; do
        case "${p%=*}" in
            LIB_TAG)
                if [ "${p#*=}" == "$(git branch | gawk -v b="${p#*=}" '{if ( $NF == b ) {print $NF}}')" ]; then
                    echo -e "[\e[0;35m warn \x1B[0m] Setting $p"
                    eval "$p"
                else
                    echo -e "[\e[0;35m warn \x1B[0m] Skip $p setting as LIB_TAG=\"\""
                    eval LIB_TAG=""
                fi
                ;;
        esac
    done
}
check_args "$@"

update_src() {
	cd "${SRC}" || exit
	if [[ ! -f "${SRC}"/.ignore_changes ]]; then
		echo -e "[\e[0;32m o.k. \x1B[0m] This script will try to update"
        # (git update logic omitted for brevity as per original script)
	fi
}

TMPFILE=$(mktemp)
chmod 644 "${TMPFILE}"
{
	echo SRC="$SRC"
	echo LIB_TAG="$LIB_TAG"
	declare -f update_src
}  > "$TMPFILE"

if [[ $(systemd-detect-virt) == 'none' ]]; then
	if [[ "${EUID}" == "0" ]]; then
		su "$(stat --format=%U "${SRC}"/.git)" -c "bash ${TMPFILE}"
	else
		bash "${TMPFILE}"
	fi
fi
rm "${TMPFILE}"

if [[ "${EUID}" == "0" ]] || [[ "${1}" == "vagrant" ]]; then
	:
elif [[ "${1}" == docker || "${1}" == dockerpurge || "${1}" == docker-shell ]] && grep -q "$(whoami)" <(getent group docker); then
	:
else
	display_alert "This script requires root privileges, trying to use sudo" "" "wrn"
	sudo "${SRC}/build.sh" "$@"
	exit $?
fi

if [ "$OFFLINE_WORK" == "yes" ]; then
	echo -e "\n"
	display_alert "* " "You are working offline."
	sleep 3s
else
	prepare_host_basic
fi

EXTER="${SRC}/external"

# Create userpatches directory if not exists
mkdir -p "${SRC}"/userpatches

cat <<'EOF' > "${SRC}"/userpatches/customize-image.sh
#!/bin/bash

echo -e "[\e[0;32m FIX \x1B[0m] Applying Network & SSH Config"

# NetworkManagerの設定
systemctl enable NetworkManager

rm -f /etc/resolv.conf
echo "nameserver 8.8.8.8" > /etc/resolv.conf
echo "nameserver 1.1.1.1" >> /etc/resolv.conf

ssh-keygen -A
systemctl enable ssh

TARGET_DIR="/opt/cix_debs"

if [ -d "$TARGET_DIR" ]; then
    echo -e "[\e[0;32m INSTALL \x1B[0m] Installing CIX packages from $TARGET_DIR..."

    apt update
    DEBIAN_FRONTEND=noninteractive apt install -y "$TARGET_DIR"/*.deb
    
    echo -e "[\e[0;32m FIX \x1B[0m] Fixing broken dependencies if any..."
    DEBIAN_FRONTEND=noninteractive apt install --fix-broken -y
    
    echo -e "[\e[0;32m INFO \x1B[0m] Deb files are kept in $TARGET_DIR"
else
    echo -e "[\e[0;33m WARN \x1B[0m] No CIX packages found at $TARGET_DIR."
    ls -l /opt
fi

echo -e "[\e[0;32m DONE \x1B[0m] Customization Complete"

exit 0
EOF

# Generate customize-image.sh
mkdir -p "${SRC}"/userpatches/overlay/etc/skel/Desktop

cat <<'EOF' > "${SRC}"/userpatches/customize-image.sh
#!/bin/bash

echo "[\e[0;32m FIX \x1B[0m] Applying Time, Network & Ubuntu Defaults"

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y fake-hwclock
date -u +'%Y-%m-%d %H:%M:%S' > /etc/fake-hwclock.data
chmod 644 /etc/fake-hwclock.data

systemctl enable systemd-timesyncd
systemctl enable NetworkManager

rm -f /etc/resolv.conf
echo "nameserver 8.8.8.8" > /etc/resolv.conf
echo "nameserver 1.1.1.1" >> /etc/resolv.conf

ssh-keygen -A


if [ -d "/tmp/cix_debs" ] && [ "$(ls -A /tmp/cix_debs/*.deb 2>/dev/null)" ]; then
    echo "[\e[0;32m INSTALL \x1B[0m] Installing CIX Drivers..."
    
    DEBIAN_FRONTEND=noninteractive apt-get install -y /tmp/cix_debs/*.deb || \
    ( echo "[\e[0;33m WARN \x1B[0m] Dependency issue detected, attempting fix..." && apt-get install -f -y )
    
    rm -rf /tmp/cix_debs
else
    echo "[\e[0;33m WARN \x1B[0m] No CIX driver packages found."
fi

echo "[\e[0;32m CLEAN \x1B[0m] Purging Orange Pi specific configs..."

PURGE_LIST="orangepi-config orangepi-zsh plymouth-theme-orangepi orangepi-wallpapers"
DEBIAN_FRONTEND=noninteractive apt-get purge -y $PURGE_LIST

if [ -f /usr/share/glib-2.0/schemas/99_orangepi_defaults.gschema.override ]; then
    rm /usr/share/glib-2.0/schemas/99_orangepi_defaults.gschema.override
    glib-compile-schemas /usr/share/glib-2.0/schemas/
fi

DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ubuntu-session gnome-session fonts-ubuntu

echo "[\e[0;32m FIX \x1B[0m] Customization Complete"
exit 0
EOF

chmod +x "${SRC}"/userpatches/customize-image.sh

# Create lib.config
if [[ ! -f "${SRC}"/userpatches/lib.config ]]; then
	cat <<-EOF > "${SRC}"/userpatches/lib.config
	PACKAGE_LIST_RM="orangepi-config orangepi-zsh plymouth-theme-orangepi orangepi-wallpapers"
    PACKAGE_LIST_ADD="network-manager openssh-server"
	PLYMOUTH="yes"
	EOF
fi

# Create config-default.conf
if [[ ! -f "${SRC}"/userpatches/config-default.conf ]]; then
    if [[ -f "${SRC}"/userpatches/config-example.conf ]]; then
         cp "${SRC}"/userpatches/config-example.conf "${SRC}"/userpatches/config-default.conf
    elif [[ -f "${EXTER}"/config/templates/config-example.conf ]]; then
         cp "${EXTER}"/config/templates/config-example.conf "${SRC}"/userpatches/config-default.conf
    else
         touch "${SRC}"/userpatches/config-default.conf
    fi
    
    cat <<-EOF >> "${SRC}"/userpatches/config-default.conf
	RELEASE="noble"
	BUILD_DESKTOP="yes"
	DESKTOP_ENVIRONMENT="gnome"
	DESKTOP_APPGROUPS_SELECTED="3dsupport browsers desktop_tools internet multimedia"
	BRANCH="current"
	EOF
fi

# Standard config loading logic
if [[ -z "${CONFIG}" && -n "$1" && -f "${SRC}/userpatches/config-$1.conf" ]]; then
	CONFIG="userpatches/config-$1.conf"
	shift
fi

if [[ -z "${CONFIG}" && -f "${SRC}/userpatches/config-default.conf" ]]; then
	CONFIG="userpatches/config-default.conf"
fi

CONFIG_FILE="$(realpath "${CONFIG}")"

if [[ ! -f "${CONFIG_FILE}" ]]; then
	display_alert "Config file does not exist" "${CONFIG}" "error"
	exit 254
fi

CONFIG_PATH=$(dirname "${CONFIG_FILE}")
source "${SRC}"/scripts/extensions.sh

display_alert "Using config file" "${CONFIG_FILE}" "info"
pushd "${CONFIG_PATH}" > /dev/null || exit
source "${CONFIG_FILE}"
popd > /dev/null || exit

[[ -z "${USERPATCHES_PATH}" ]] && USERPATCHES_PATH="${CONFIG_PATH}"

while [[ "${1}" == *=* ]]; do
	parameter=${1%%=*}
	value=${1##*=}
	shift
	display_alert "Command line: setting $parameter to" "${value:-(empty)}" "info"
	eval "$parameter=\"$value\""
done

if [[ "${BUILD_ALL}" == "yes" || "${BUILD_ALL}" == "demo" ]]; then
	source "${SRC}"/scripts/build-all-ng.sh
else
	source "${SRC}"/scripts/main.sh
fi